### ISSUE TITLE
Is this code working?

### ISSUE THREAD

**Issue by boboxx** [kolins-cz/Smart-BMS-Bluetooth-ESP32#1]
Is this code working? I'm trying to compile it under PlatformIo and the re seems to be a lot of invalid includes.

**Comment by kolins-cz** [comment]
Hi. Yes code works. I never used PlatformIo. It is compiled in standard Arduino 1.6.x with ESP32 support package a TFT_eSPI library.

While this works, it is unfinished and more of a reference for others. I used on my e-bike for more than year.
